#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-chill_2.12
Version  : 8.2.0
Release  : 1
URL      : https://repo.maven.apache.org/maven2/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.jar
Source0  : https://repo.maven.apache.org/maven2/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.jar
Source1  : https://repo.maven.apache.org/maven2/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-chill_2.12-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-chill_2.12 package.
Group: Data

%description data
data components for the mvn-chill_2.12 package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.jar
/usr/share/java/.m2/repository/com/twitter/chill_2.12/0.7.6/chill_2.12-0.7.6.pom
